apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: postgres-ingress
  namespace: postgres
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: postgres.johanhernandez.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: postgres-cluster-rw
                port:
                  number: 5432
